# Generated by Django 4.2.2 on 2024-07-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_username_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
