# Generated by Django 4.2.2 on 2024-07-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_login_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
